version: "3"
services:
  analysis:
    image: joelnitta/canopylife:3.6.0
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/rstudio/canopylife"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/rstudio/canopylife
