\documentclass{article}

% Set margins
\usepackage[margin=1in]{geometry}

% Enable bibliography
\usepackage{natbib} 

% Set unit and abbreviations formatting
\input{table_style}

\begin{document}

<<setup, echo=FALSE>>=
# setup knitr
library(knitr)
opts_knit$set(concordance=FALSE)
opts_chunk$set(echo=FALSE)
opts_chunk$set(message=FALSE)
opts_chunk$set(warning=FALSE)
@

%%%%%%%%%%%%%%%%%%%%%%%%%%% Tables %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<setup_tables>>=
library(xtable)
setwd(here::here())
source("bin/latex_functions.R")
# load results objects produced by running manuscript.Rnw
load("results.RData")
@

% Table 1
\clearpage

\begin{table}[ht]
\centering
\caption{Traits used in this study. Noncordate gametophyte morphotypes include ribbon, strap and filamentous.}
\begin{tabular}{ p{0.3\textwidth} p{0.2\textwidth} p{0.4\textwidth} }
\hline
 & Data type (unit) & Ecological Significance \\
\hline
Sporophyte Traits & & \\
\hspace{3ex}Stipe Length  & Continuous (cm)  & Shorter stipes compensate for low conductivity \citep{WatkinsJr.2010} \\
\hspace{3ex}Frond Length  & Continuous (cm)  & Smaller leaf size reduces evapotranspiration \citep{Vogel1968} \\
\hspace{3ex}Frond Width  & Continuous (cm)  & Smaller leaf size reduces evapotranspiration \citep{Vogel1968} \\
\hspace{3ex}Rhizome Diameter  & Continuous (cm)  & Scales with overall plant size (Creese et al. 2011) \\
\hspace{3ex}Frond Dissection  & Ordinal  & Simple laminae reduce evapotranspiration (Kluge and Kessler 2007) \\
\hspace{3ex}Pinna number & Integer & Scales with overall plant size (Creese et al. 2011) \\
\hspace{3ex}Specific Leaf Area & Continuous (m\textsuperscript{2} kg\textsuperscript{-1}) & Species in more stressful environments invest in thicker leaves \citep{Wright2004a} \\
Gametophyte Traits & & \\
\hspace{3ex}Morphotype & Binary (cordate vs. noncordate) & Noncordate morphology reduces drying rates by holding external water in crevices and folds \citep{WatkinsJr.2007,Pittermann2013} \\
\hspace{3ex}Gemmae & Binary (present/absent) & Enable asexual reproduction, thereby overcoming local extinction due to drying \citep{Farrar2008} \\
\hspace{3ex}Glands & Binary (present/absent) & Lipophilic exudates produced by glands may reduce transpiration rates \citep{Wollenweber2000} \\
\hspace{3ex}Hairs & Binary (present/absent) & Hairs reduce drying rates by holding external water and increasing boundary layer thickness \citep{WatkinsJr.2007} \\
\hline
\end{tabular}
\label{table:traits}
\end{table}

% Table 2
\clearpage

<<cont_phylosig, results="asis">>=
cont_phylosig.results <- round_df(cont_phylosig.results)
cont_phylosig.results <- embolden_p(cont_phylosig.results, col.select=c("k.pval","lambda.pval"))
part_label <- add_part_label(cont_phylosig.results, "(a)")
  
print(xtable(cont_phylosig.results,
             label="table:phylosig",
             caption="Phylogenetic signal in traits. (a) Continuous traits and (b) binary traits. Values of $\\lambda$ or $\\K >= 1$ indicate that traits are evolving according to Brownian Motion (BM); values of $\\lambda$ or \\K near 0 indicate random distribution of traits. For \\D, values of 0 (or less) indicate evolution according to (or more conserved than) BM; values near 1 indicate random trait distribution. \\pval\\textsubscript{Rnd}, result of testing that observed \\D is significantly different from 1; \\pval\\textsubscript{BM}, result of testing that observed \\D is significantly different from 0."),
      sanitize.colnames.function = custom_cols,
      sanitize.rownames.function = custom_rows,
      sanitize.text.function = function (x) {x},
      include.rownames=TRUE,
      add.to.row = part_label,
      caption.placement="top")
@

<<binary_phylosig, results="asis">>=
binary_phylosig.results <- round_df(binary_phylosig.results)
binary_phylosig.results <- embolden_p(binary_phylosig.results, col.select=c("prob_random","prob_browian"))
part_label <- add_part_label(binary_phylosig.results, "(b)")
  
print(xtable(binary_phylosig.results,
             caption=NULL),
      sanitize.colnames.function = custom_cols,
      sanitize.rownames.function = custom_rows,
      sanitize.text.function = function (x) {x},
      include.rownames=TRUE,      
      add.to.row = part_label)
@

% Table 3
\clearpage

<<sporo_PIC, results="asis">>=
PIC.results <- round_df(PIC.results)
PIC.results <- embolden_p(PIC.results, col.select=c("pval"))

print(xtable(PIC.results,
             label="table:PIC_sporo",
             caption="Results of phylogenetically independent contrasts analysis of quantitative (sporophyte) traits related to epiphytic growth. All trait contrasts were made by subtracting epiphytic values from terrestrial values; thus, a positive contrast indicates greater values for terrestrial clades. Significant differences between epiphytes and terrestrial clades in bold."),
      sanitize.colnames.function = custom_cols,
      sanitize.rownames.function = custom_rows,
      sanitize.text.function = function (x) {x},
      include.rownames=TRUE,
      caption.placement="top")
@


%%%%%%%%%%%%%%%%%%%%%%%%%%% Appendix Tables %%%%%%%%%%%%%%%%%%%%%%
% Add S to table number and reset counter
\renewcommand{\thetable}{S\arabic{table}}
\setcounter{table}{0}

% Table S1
\clearpage

<<PGLMM, results="asis">>=
# read in results from running PGLMM on cluster, clean up dataframe
pglmm.results <- read.csv("data/mcmcglmm_habit_all_results.csv")
pglmm.results <- pglmm.results[pglmm.results$Effect == "habit", ]
pglmm.results$Effect <- NULL
pglmm.results$Model <- gsub(" ~ habit", "", pglmm.results$Model)
pglmm.results$Model <- tolower(pglmm.results$Model)
rownames(pglmm.results) <- pglmm.results$Model
pglmm.results$Model <- NULL

# add latex formatting
pglmm.results <- round_df(pglmm.results)
pglmm.results <- embolden_p(pglmm.results, col.select="P.value")

print(xtable(pglmm.results,
             label="supp_table:PGLMM_sporo",
             caption="Phylogenetic generalized linear mixed models (PGLMMs) for quantitative (sporophyte) traits related to epiphytic growth. The response of each trait was modeled against growth habit using a PGLMM with phylogeny as a random effect. \\pval for traits significantly correlated with growth habit in bold."),
      sanitize.text.function = function (x) {x},
      sanitize.colnames.function = custom_cols,
      sanitize.rownames.function = custom_rows,
      include.rownames=TRUE,
      caption.placement="top")

@

% Table S2
\clearpage

<<binaryPGLMM, results="asis">>=
bpglmm.results <- round_df(bpglmm.results)
bpglmm.results <- embolden_p(bpglmm.results, col.select=c("sigmap","pvalue"))

print(xtable(bpglmm.results,
             label="supp_table:PGLMM_gameto",
             caption="Phylogenetic generalized linear mixed models (PGLMMs) for binary (gametophyte) traits traits related to epiphytic growth. The response of each trait was modeled against growth habit using a PGLMM with phylogeny as a random effect. $\\sigma^2$ is a measure of phylogenetic signal calculated from the variance in the PGLMM. Significance of $\\sigma^2$ calculated using an approximate likelihood ratio test between a model with the observed value of $\\sigma^2$ against a null model with $\\sigma^2 = 0$. Statistically significant values in bold."),
      sanitize.text.function = function (x) {x},
      sanitize.colnames.function = custom_cols,
      sanitize.rownames.function = custom_rows,
      include.rownames=TRUE,
      caption.placement="top")
@

% Table S3
\clearpage

<<climate_ancova, results="asis">>=
ancova.results <- round_df(ancova.results)
ancova.results <- embolden_p(ancova.results, col.select=c("pval.intercept","pval.slope"))
part_label <- add_part_label(ancova.results , "(a)")

print(xtable(ancova.results,
             label="supp_table:climate_model",
             caption="Results of analysis of covariance (ANCOVA) for microclimatic variables between epiphytic and terrestrial plots along an elevational gradient on Moorea, French Polynesia. (a) Model statistics and (b) estimates. Linear models were constructed for each response variable with growth habit as a fixed effect and elevation as a co-factor. Differences in intercept between growth habits was tested with models of the form $y \\sim growth habit + elevation$. Differences in slope between growth habits were tested with models of the form $y \\sim growth habit \\times elevation$. Models were compared using the `aov' function in R."),
      sanitize.colnames.function = custom_cols,
      sanitize.rownames.function = custom_rows,
      sanitize.text.function = function (x) {x},
      include.rownames=TRUE,
      add.to.row = part_label,
      caption.placement="top")
@

<<climate_slopes, results="asis">>=
slopes.results <- round_df(slopes.results)
part_label <- add_part_label(slopes.results , "(b)")

print(xtable(slopes.results,
             caption=NULL),
      sanitize.colnames.function = custom_cols,
      sanitize.rownames.function = custom_rows,
      add.to.row = part_label,
      include.rownames=TRUE)
@

% Table S4
\clearpage

<<trait_pca, results="asis">>=
PCA.results <- round_df(PCA.results)
PCA.results <- embolden_top_values(PCA.results, row.select = c("dissection", "length", "pinna", "rhizome", "sla", "stipe", "width"))

print(xtable(PCA.results,
             label="supp_table:PCA",
             caption="PC loadings for principal components analyses (PCA) of traits related to epiphytic growth in ferns from Moorea, French Polynesia. For each PC, values of the three traits with the greatest loadings (absolute values) shown in bold."),
      sanitize.text.function = function (x) {x},
      sanitize.colnames.function = custom_cols,
      sanitize.rownames.function = custom_rows,
      include.rownames=TRUE,
      caption.placement="top")
@

%%%%%%%%%%%%%%%%%%%%%%%%%%% Refs in Tables %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\bibliographystyle{newphyt} 
\bibliography{references} 

\end{document}