library(conflicted)
library(FD)
library(FSSgam)
library(FactoMineR)
library(RColorBrewer)
library(assertr)
library(assertthat)
library(broom)
library(caper)
library(corrr)
library(cowplot)
library(drake)
library(ggrepel)
library(ggtree)
library(glue)
library(janitor)
library(jntools)
library(magrittr)
library(mgcv)
library(mooreaferns)
library(patchwork)
library(phytools)
library(picante)
library(plantecophys)
library(scales)
library(scico)
library(sme)
library(sp)
library(spdep)
library(viridis)
library(tidyverse)

conflict_prefer("filter", "dplyr")
conflict_prefer("gather", "tidyr")
conflict_prefer("standard_theme", "jntools")
conflict_prefer("map", "purrr")
conflict_prefer("select", "dplyr")
conflict_prefer("ggsave", "ggplot2")
