library(conflicted)
library(mooreaferns)
library(tidyverse)
library(drake)
library(glue)
library(RColorBrewer)
library(jntools)
library(patchwork)
library(broom)

conflict_prefer("filter", "dplyr")
conflict_prefer("gather", "tidyr")
conflict_prefer("standard_theme", "jntools")